### ISSUE TITLE
Navigate mode.

### ISSUE THREAD

**Issue by bwplotka** [paxtonhare/demo-magic#15]
Hi :wave:  

Thanks for this project! :beers: 

For my demo purposes I changed your script drastically to more "navigate" like (interactive) mode. You can see the script here: https://gist.github.com/bwplotka/c2021c9411ac10cc45ff24aa0e32837a

The goal for me was to be able to fast forward and fast backward any time during the demo. There are numerous cases like:
* Commands needs to be retried suddenly
* Someone from audience wants to reply some bit of demo
* I want to show something in detail
.. and probably more.

I am adding this issue to ask if you want to support such cases in your project? Would you like to add this script here? I could host it in my own github repo, but since the code and idea is inspired by your bash code, I am happy to contribute it here if you obviously want such contribution.

Note I am not bash master, it that does not allow flexible options and probably does not work across all, gazillion shell versions and distros etc etc (: So it would need some touches.

Cheers!

**Comment by aspiers** [comment]
[**@bwplotka**](https://github.com/bwplotka) commented on [February 4, 2019 8:27 PM](https://github.com/paxtonhare/demo-magic/issues/15#issuecomment-460400150 "2019-02-04T20:27:23Z - Replied by Github Reply Comments"):
> I guess that silence means "no" ):

I really don't know in this case, but based on many years of experience with open source projects (both mine and others) I would say that it's far more likely that silence simply means that the maintainer hasn't had a chance to reply yet.  It's not uncommon to have to wait multiple weeks or even months for a reply.

**Comment by bwplotka** [comment]
Agree and happy to change things once maintainer will reply (:

**Comment by bwplotka** [comment]
https://github.com/bwplotka/demo-nav
