### ISSUE TITLE
Keep default prompt

### ISSUE THREAD

**Issue by dkirrane** [paxtonhare/demo-magic#16]
Is there a way to keep my default prompt between each step?

I've tried the following in my script but it results in now prompt at all:
```
. ~/demo-magic.sh
DEMO_PROMPT="${PS1}"
pe "ls -l"
pe "echo 'Hello'"
```

**Comment by davinkevin** [comment]
I have the same problem

**Comment by paxtonhare** [comment]
Looks like $PS1 isn't available inside child scripts. I'd recommend setting DEMO_PROMPT to the actual value of your PS1.

So do an `echo $PS1` in your terminal. then hand jam that value into your script.
