### ISSUE TITLE
Suggestion command for print+eval+nowait

### ISSUE THREAD

**Issue by alex0ptr** [paxtonhare/demo-magic#19]
Thanks for the cool script.

I wanted a few commands to execute directly. The suggested option in the Readme using `wait` however causes the cursor on my shell to jump to the next line without prompt. This breaks the illusion of me typing. Also I didn't really like that I had to put a wait after each command when I wanted to opt in for NO_WAIT. Hence I defined a function:

```sh
# print and execute immediately
function pei {
    NO_WAIT=true pe $1
}

# usage
pei "cd agilebank" 
```

What do you think, could this be a nice addition? I'm happy to provide a pull request with updated docs.

**Comment by paxtonhare** [comment]
@alex0ptr I went ahead and added the feature. I figure too much time had passed to bother you with doing it. Thanks for the suggestion!
