### ISSUE TITLE
Would like to pay you a beer ;)

### ISSUE THREAD

**Issue by jalogut** [paxtonhare/demo-magic#9]
Hi, 

Thanks for this great tool. It helped me a lot to automate a live demo for a Webminar.
Would you add a paypal badge in the `README`, so I can pay you a beer?

* https://github.com/patharanordev/donate-in-git

**Comment by rdodev** [comment]
Paypal, Venmo or other types of donation channels. This is a really neat tool 🍺 donation is deserved.

**Comment by paxtonhare** [comment]
@jalogut thanks for the kind words. Just pay it forward.
